[package]
name = "hi_cargo"
version = "0.1.0"
authors = ["cdyfng <xiaofeng_chen2007@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
